apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://gitlab.com/biletado/kustomize.git//overlays/kind?ref=main

configMapGenerator:
  - name: replacements
    literals:
      - POSTGRES_ASSETS_DBNAME=assets_v2

# https://stackoverflow.com/a/78742842/568291
replacements:
  - source:
      kind: ConfigMap
      name: replacements
      fieldPath: data.POSTGRES_ASSETS_DBNAME
    targets:
      - select:
          group: apps
          version: v1
          kind: Deployment
          name: assets
        fieldPaths:
          - spec.template.spec.containers.[name=assets].env.[name=POSTGRES_ASSETS_DBNAME].value
patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: registry.gitlab.com/biletado/backend/assets/the-real-one:latest
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
    target:
      group: apps
      version: v1
      kind: Deployment
      name: assets
