apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://gitlab.com/biletado/kustomize.git//overlays/kind

patches:
  - target:
      kind: Deployment
      name: assets
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: example.com/alocalimage:local-dev
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
